language: c

before_install:
- wget http://downloads.sourceforge.net/project/cunit/CUnit/2.1-2/CUnit-2.1-2-src.tar.bz2
- tar -xvjpf CUnit-2.1-2-src.tar.bz2
- cd CUnit-2.1-2
- ./configure --prefix=$TRAVIS_BUILD_DIR
- make
- make install
- export C_INCLUDE_PATH=$TRAVIS_BUILD_DIR/include:$C_INCLUDE_PATH
- export LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LIBRARY_PATH
- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LD_LIBRARY_PATH
- cd ..
- pip install --user cpp-coveralls

script:
- make && make test

after_success:
- coveralls --exclude lib --exclude tests --gcov-options '\-lp'


