dist: trusty
sudo: required
language: c

compiler:
- gcc
- clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - gcc-8
      - g++-8
      - cmake
      - clang-6.0
      - clang++-6.0
env:
  global:
      - CODECOV_TOKEN=5a7a6637-fa92-4356-9651-0da0d491ba0d

before_install:
- sudo apt-get install xsltproc valgrind
- wget http://downloads.sourceforge.net/project/cunit/CUnit/2.1-2/CUnit-2.1-2-src.tar.bz2
- tar -xvjpf CUnit-2.1-2-src.tar.bz2
- cd CUnit-2.1-2
- ./configure --prefix=$TRAVIS_BUILD_DIR
- make
- make install
- export C_INCLUDE_PATH=$TRAVIS_BUILD_DIR/include:$C_INCLUDE_PATH
- export LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LIBRARY_PATH
- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LD_LIBRARY_PATH
- cd ..

script:
- ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
- ln -s /usr/bin/g++-8 /usr/local/bin/g++
- ln -s /usr/bin/clang-6.0 /usr/local/bin/clang
- ln -s /usr/bin/clang++-6.0 /usr/local/bin/clang++
- cmake . -Bbuild/
- cd build/
- make
- cd ..
- make && make test && ./ooc
- gcov *.o src/*.o test/*.o
- make xunit-report
- cat TestResults.xml

after_success:
- bash <(curl -s https://codecov.io/bash)

